#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EDHMTGLifeCounter.Resource", IsApplication=true)]

namespace EDHMTGLifeCounter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int magic_the_gathering_online = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int btnAddAmount = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int btnAddAmountDialog = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int btnAddOne = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int btnCancelDiag = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int btnCancelDialog = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int btnOkayDiag = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int btnReset = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int btnSubtractOne = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int tableLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tableRow1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int tableRow2 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow3 = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int textView1 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int txtAmountDialog = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int txtHealth = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layAmount = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layAreYouSure = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layCommander = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layPoison = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LifeCounter = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
